config/routes.rb
Rails.application.routes.draw do
  # admin
  namespace :admin do
    root to: 'home#index'
    resources :posts do
      member do
      post 'report' 
      end
    end
    resources :categories
    resources :users
  end

  #user
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }
  root "home#index"
  resources :posts do
  resources :comments, only: [:create]
  end
  resources :profile , only: [:index]
  resources :about , only: [:index]


  require "sidekiq/web"
  mount Sidekiq::Web => "/sidekiq"

end

app/models/post.rb
class Post < ApplicationRecord
    attribute :published, :boolean, default: true

    belongs_to :user
    belongs_to :category
    has_many :comments, dependent: :destroy


    validates :title, presence: true, length: { minimum: 5, maximum: 100 }
    validates :content, presence: true

    scope :published, -> { where(published: true) }
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::BaseController
  load_and_authorize_resource

  before_action :authenticate_user!, except: [:index]
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authorize_user, only: [:edit, :update, :destroy]  

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    # @post = current_user.posts.build(post_params)  # Gán user_id từ current_user
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to admin_posts_path, notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to admin_post_path(@post), notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_url, notice: 'Post was successfully destroyed.'
  end

def report
  post = Post.find(params[:id])
  user = post.user
  
  puts "==== USER EMAIL: #{user.email}, POST ID: #{post.id}"  
  
  Rails.logger.info "Reporting post #{post.id} by user #{user.id} (#{user.email})"
  
  UserMailer.report_violation_email(user, post).deliver_now
  
  Rails.logger.info "====== EMAIL SENT DIRECTLY ======"
  
  # Redirect lại trang admin post với thông báo
  redirect_to admin_posts_path, notice: 'The post has been reported. The user will be notified shortly.'
end
  private

  def set_post
    @post = Post.find(params[:id])  # Lấy bài viết theo ID
  end

  def post_params
    params.require(:post).permit(:title, :content, :category_id, :published)  # Các tham số cho bài viết
  end

  def authorize_user
    # Kiểm tra nếu bài viết thuộc về người dùng hiện tại hay không
    unless @post.user_id == current_user.id
      redirect_to posts_path, alert: "Bạn không có quyền chỉnh sửa hoặc xóa bài viết này."
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authorize_user, only: [:edit, :update, :destroy]  

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    # @post = current_user.posts.build(post_params)  # Gán user_id từ current_user
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to posts_path, notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_url, notice: 'Post was successfully destroyed.'
  end

  private

  def set_post
    @post = Post.find(params[:id])  # Lấy bài viết theo ID
  end

  def post_params
    params.require(:post).permit(:title, :content, :category_id, :published)  # Các tham số cho bài viết
  end

  def authorize_user
    # Kiểm tra nếu bài viết thuộc về người dùng hiện tại hay không
    unless @post.user_id == current_user.id
      redirect_to posts_path, alert: "Bạn không có quyền chỉnh sửa hoặc xóa bài viết này."
    end
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/views/admin/posts/edit.html.slim
h1.text-3xl.font-bold.text-center.mb-6 Edit Post

= form_with model: @post, url: admin_post_path(@post), method: :put, local: true, html: { class: 'max-w-3xl mx-auto p-6 bg-white shadow-md rounded-lg' } do |form|
  - if @post.errors.any?
    .bg-red-100.border-l-4.border-red-500.text-red-700.px-4.py-2.rounded-md
      h2 = pluralize(@post.errors.count, "error") + " prohibited this post from being saved"
      ul
        - @post.errors.full_messages.each do |message|
          li = message

  / Title
  .mb-4
    = form.label :title, class: 'block text-sm font-semibold text-gray-700'
    = form.text_field :title, class: 'mt-1 block w-full px-4 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-400 focus:outline-none'

  / Content
  .mb-4
    = form.label :content, class: 'block text-sm font-semibold text-gray-700'
    = form.text_area :content, class: 'mt-1 block w-full px-4 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-400 focus:outline-none', rows: 6

  / Category
  .mb-4
    = form.label :category_id, class: 'block text-sm font-semibold text-gray-700'
    = form.collection_select :category_id, Category.all, :id, :name, prompt: 'Select Category', class: 'mt-1 block w-full px-4 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-400 focus:outline-none'

  .mt-6.flex.justify-between
    = form.submit 'Update Post', class: 'px-6 py-3 bg-green-500 text-white font-semibold rounded-md hover:bg-green-600 focus:outline-none focus:ring-2 focus:ring-green-400 transition'
    
    = link_to admin_post_path(@post), class: 'px-6 py-3 text-gray-700 rounded-md focus:outline-none focus:ring-2 focus:ring-gray-400 transition flex items-center' do
      i.fa.fa-arrow-left.mr-2

app/views/admin/posts/index.html.slim
/ Tiêu đề và nút New Post
div.relative.mb-6.flex.items-center.justify-center
  h1.text-3xl.font-bold Admin - Posts
  = link_to new_admin_post_path,
    class: 'absolute right-0 px-4 py-2 bg-green-500 text-white rounded hover:bg-green-600 transition space-x-2 flex items-center' do
    i class="fa-solid fa-plus"
    span New Post

/ Bảng danh sách bài viết
div.container.mx-auto.px-8
  div.overflow-x-auto
    table.w-full.text-left.text-sm.bg-white.shadow-md.rounded-lg
      thead.bg-gray-100
        tr
          th.px-6.py-3 Title
          th.px-6.py-3 Content
          th.px-6.py-3 Author
          th.px-6.py-3 Category
          th.px-6.py-3 Created At
          th.px-6.py-3 Actions
      tbody
        - @posts.each do |post|
          tr.border-b
            td.px-6.py-4.font-medium.text-gray-800 = post.title.truncate(30, separator: ' ')
            td.px-6.py-4.font-medium.text-gray-800 = post.content.truncate(100, separator: ' ')
            td.px-6.py-4 = post.user.email
            td.px-6.py-4 = post.category.name
            td.px-6.py-4 = l(post.created_at, format: :short)
            td.px-6.py-4.flex.items-center.space-x-4
              / Show
              = link_to admin_post_path(post), class: 'text-blue-500 hover:scale-110 transition' do
                i class="fa-solid fa-eye text-lg" title="Show"

              / Edit
              = link_to edit_admin_post_path(post), class: 'text-green-500 hover:scale-110 transition' do
                i class="fa-solid fa-pen text-lg" title="Edit"

              / Delete
              = button_to admin_post_path(post), method: :delete,
                  data: { turbo_confirm: 'Are you sure?' },
                  form_class: "inline-block", class: 'text-red-500 hover:scale-110 transition' do
                i class="fa-regular fa-trash-can text-lg" title="Delete"

              / Report 
              = button_to report_admin_post_path(post), method: :post, class: 'text-yellow-500 hover:scale-110 transition inline-flex items-center', data: { turbo_confirm: 'Are you sure you want to report this post?' } do
                i class="fa-solid fa-flag text-lg" title="Report"

app/views/admin/posts/new.html.slim
/ H1 căn giữa, in đậm
h1.text-3xl.font-bold.text-center.mb-6 New Post

= form_with model: @post, url: admin_posts_path, method: :post, local: false, html: { class: 'max-w-3xl mx-auto p-6 bg-white shadow-md rounded-lg' } do |form|
  - if @post.errors.any?
    .bg-red-100.border-l-4.border-red-500.text-red-700.px-4.py-2.rounded-md
      h2 = pluralize(@post.errors.count, "error") + " prohibited this post from being saved"
      ul
        - @post.errors.full_messages.each do |message|
          li = message

  / Trường Title
  .mb-4
    = form.label :title, class: 'block text-sm font-semibold text-gray-700'
    = form.text_field :title, class: 'mt-1 block w-full px-4 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-400 focus:outline-none'

  / Trường Content
  .mb-4
    = form.label :content, class: 'block text-sm font-semibold text-gray-700'
    = form.text_area :content, class: 'mt-1 block w-full px-4 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-400 focus:outline-none', rows: 6

  / Trường Category
  .mb-4
    = form.label :category_id, class: 'block text-sm font-semibold text-gray-700'
    = form.collection_select :category_id, Category.all, :id, :name, prompt: 'Select Category', class: 'mt-1 block w-full px-4 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-400 focus:outline-none'

  / Submit và nút quay lại
  .mt-6.flex.justify-between
    = form.submit 'Create Post', class: 'px-6 py-3 bg-green-500 text-white font-semibold rounded-md hover:bg-green-600 focus:outline-none focus:ring-2 focus:ring-green-400 transition'
    
    = link_to admin_posts_path, class: 'px-6 py-3 text-gray-700 rounded-md focus:outline-none focus:ring-2 focus:ring-gray-400 transition flex items-center' do
      i.fa.fa-arrow-left.mr-2

app/views/admin/posts/show.html.slim
/ H1 căn giữa, in đậm
h1.text-3xl.font-bold.text-center.mb-6 Post Details

div.bg-white.p-6.shadow-md.rounded-lg
  h2.text-xl.font-semibold.mb-4 = @post.title

  div.mb-4
    strong Category:
    = @post.category.name

  div.mb-4
    strong Author:
    = @post.user.email

  div.mb-4
    strong Created At:
    = l(@post.created_at, format: :long)

  div.mb-4
    strong Content:
    p = @post.content

  / Actions
  div.flex.justify-between.mt-6
    = link_to admin_posts_path, class: 'text-gray-500 hover:underline' do
      i class="fa-solid fa-arrow-left mr-2" 
      span Back to Posts